# Generated by Django 4.2.17 on 2025-01-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='password_1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='password_2',
        ),
    ]
