# Generated by Django 4.2.17 on 2025-02-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_password_1_userregister_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='shop_address',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='shop_city',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='shop_state',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userregister',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Vendor Shop Name')),
                ('shop_state', models.CharField(max_length=100, verbose_name='Vendor Shop State')),
                ('shop_city', models.CharField(max_length=100, verbose_name='Vendor Shop City')),
                ('shop_address', models.CharField(max_length=100, verbose_name='Vendor Shop Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.userregister')),
            ],
        ),
    ]
