# Generated by Django 4.2.17 on 2025-02-24 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userregister_shop_address_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userregister', verbose_name='Cart User')),
            ],
        ),
        migrations.AlterField(
            model_name='wastecategory',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('image', models.ImageField(upload_to='product/images', verbose_name='Product Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('stock', models.IntegerField(verbose_name='Product Stock')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Weight')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.wastecategory', verbose_name='Product Category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendor', verbose_name='Product Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('quantity', models.IntegerField(default=1, verbose_name='Cart Items')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
        ),
    ]
