# Generated by Django 4.2.17 on 2025-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cart_alter_wastecategory_category_product_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastecategory',
            options={'verbose_name': 'waste categories', 'verbose_name_plural': 'waste categories'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
