# Generated by Django 4.2.17 on 2025-04-08 12:59

from django.db import migrations, models

def set_default_values(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    for obj in Product.objects.all():
        obj.available = int(obj.weight)
        obj.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_wastecategory_options_cartitem_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.IntegerField(blank=True, null=True, verbose_name='Available Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Per unit weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Product Weight'),
        ),
    ]
